AllCops:
  NewCops: enable

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
